download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv", destfile="idaho-housing.csv")
data <- data.frame(read.csv('idaho-housing.csv'))
data <- data.table(data)
nrow(data[VAL == 24 & !is.na(VAL)])
download.file('https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FDATA.gov_NGAP.xlsx')
dat <- read.xlsx('natural-gaz-acquisition.xlsx', sheetIndex = 1, startRow = 18, endRow = 23, colIndex =7:15)
sum(dat$Zip*dat$Ext,na.rm=T)
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml", destfile="restaurants.xml")
data <- xmlParse("restaurants.xml")
xmltop <- xmlRoot(data)
res <- xpathSApply(xmltop, '//zipcode', xmlValue)
sum(res == "21231")